# Generated by Django 5.2.8 on 2025-11-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date_notified"]},
        ),
    ]
