# Generated by Django 5.2.8 on 2025-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('report', 'Report'), ('disaster', 'Disaster')], default='disaster', max_length=40),
        ),
    ]
