# Generated by Django 5.2.8 on 2025-11-08 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=80)),
                ('longitude', models.CharField(max_length=80)),
                ('formatted_location_string', models.TextField(blank=True, null=True)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
