# Generated by Django 5.2.8 on 2025-11-08 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(max_length=80)),
                ("longitude", models.CharField(max_length=80)),
                ("formatted_location_string", models.TextField(blank=True, null=True)),
                ("magnitude", models.DecimalField(decimal_places=2, max_digits=3)),
                ("date_recorded", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("date_recorded",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField()),
                ("latitude", models.CharField(max_length=80)),
                ("longitude", models.CharField(max_length=80)),
                ("formatted_location_string", models.TextField(blank=True, null=True)),
                (
                    "date_reported",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
