# Generated by Django 5.2.8 on 2025-11-08 05:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'latitude', 'longitude', 'date_reported')},
        ),
    ]
