# Generated by Django 5.2.8 on 2025-11-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disaster',
            options={'ordering': ('id',)},
        ),
    ]
