# Generated by Django 5.2.8 on 2025-11-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0003_report_date_reported_alter_report_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disaster',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
