# Generated by Django 5.2.8 on 2025-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0003_alter_disaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=50),
        ),
    ]
