# Generated by Django 5.2.8 on 2025-11-08 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0004_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
