# Generated by Django 5.2.8 on 2025-11-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disasters', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disaster',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
