# Generated by Django 5.2.8 on 2025-11-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userpreference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='minimum_magnitude',
            new_name='magnitude_range',
        ),
    ]
