# Generated by Django 5.2.8 on 2025-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_minimum_magnitude_userpreference_magnitude_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='alert_types',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('major', 'Major')], default='minor', max_length=20),
        ),
    ]
